ENV['IOS_FIREBASE_DEV_APP_ID'] = 'firebase_ios_dev_app_id'
ENV['IOS_FIREBASE_STAGE_APP_ID'] = 'firebase_ios_stage_app_id'
ENV['IOS_FIREBASE_PROD_APP_ID'] = 'firebase_ios_prod_app_id'
ENV['ANDROID_FIREBASE_DEV_APP_ID'] = 'firebase_android_dev_app_id'
ENV['ANDROID_FIREBASE_STAGE_APP_ID'] = 'firebase_android_stage_app_id'
ENV['ANDROID_FIREBASE_PROD_APP_ID'] = 'firebase_android_prod_app_id'